(load "./1.35.scm")
(load "./scheme.helper.scm")
(define (deriv g)
    (lambda (x) (/ (- (g (+ x dx)) (g x)) dx)))
(define dx 0.00001)
; 求导数
(define (newton-transform g)
    (lambda (x) (- x (/ (g x) ((deriv g) x))))
)
(define (newtons-method g guess)
    (fixed-point (newton-transform g) guess))
(define (cubic a b c)
    (lambda (x)
        (+ (cube x)
            (* a (square x))
            (* b x)
            c
        )
    )     
)
(display (newtons-method (cubic 3 2 1) 1.0))