(define (make-segment x y)
    (cons x y)
)

(define (x-point segment)
    (car segment)    
)
(define (y-point segment)
    (cdr segment)    
)

(define (print-point p)
    (newline)
    (display "(")
    (display (x-point p))
    (display ",")
    (display (y-point p))
    (display ")")    
)
(define (midpoint-segment p1 p2)
    (make-segment 
        (/ (+ (x-point p1) (x-point p2)) 2)
        (/ (+ (y-point p1) (y-point p2)) 2)
    )
)
(define f-point (make-segment 5 9)
)
(define t-point (make-segment 7 1)
)
; (display (print-point (midpoint-segment f-point t-point)))